spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://101.101.210.91:3306/DEV
    username: DEV_USER
    password: pass@word1
    driver-class-name: org.mariadb.jdbc.Driver

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**