spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mariadb://101.101.210.91:3306/DEV
    username: DEV_USER
    password: pass@word1
    driver-class-name: org.mariadb.jdbc.Driver