server:
  port: 8080
# Swagger springdoc-ui Configuration
# swaggerdoc
springdoc:
  packages-to-scan: com.jagiya.main.controller
  swagger-ui.path: /api-docs
#  swagger-ui:
#    tags-sorter: alpha
#    operations-sorter: alpha
#    display-query-params-without-oauth2: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mariadb://101.101.210.91:3306/DEV
    username: DEV_USER
    password: pass@word1
    driver-class-name: org.mariadb.jdbc.Driver

