name: Merge On Done

on:
  issues:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to develop
      if: startsWith(github.event.issue.title, 'issue-')
      run: |
        branch="issue-${{ github.event.issue.number }}/done"
        git fetch origin $branch:$branch
        git checkout develop
        git merge $branch --no-edit
        git push origin develop
